"use client";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, BookOpen, Check, FileText, Globe2, MessageSquare, Plus, Quote, Sparkles, Upload } from "lucide-react";
import { motion, useReducedMotion } from "framer-motion";

function NotebookPreview() {
  return <div className="mx-auto mt-12 max-w-[900px] overflow-hidden rounded-xl border border-stone-200 bg-white text-left shadow-[0_24px_70px_#3931430b] ring-6 ring-violet-200/10 max-sm:mt-8 dark:border-zinc-700 dark:bg-zinc-900" aria-label="Illustration of a notebook conversation">
    <div className="flex items-center justify-between border-b border-stone-200 px-5 py-3.5 text-[10px] text-stone-500 dark:border-zinc-700 dark:text-zinc-400 [&>span:first-child]:flex [&>span:first-child]:items-center [&>span:first-child]:gap-2"><span><span className="inline-block size-1.5 rounded-full bg-[#82967a] ring-3 ring-[#82967a15]" /> A little space for big ideas</span><span className="text-[8px] tracking-widest max-sm:hidden">NOTEBOOK PREVIEW</span></div>
    <div className="grid min-h-[330px] grid-cols-[285px_1fr] max-sm:grid-cols-1">
      <aside className="border-r border-stone-200 bg-stone-50/80 px-4 pb-4 pt-6 max-sm:hidden dark:border-zinc-700 dark:bg-zinc-950/30 [&>div:first-child]:mb-5 [&>div:first-child]:flex [&>div:first-child]:justify-between"><div className="text-[9px] font-semibold tracking-[.16em] text-stone-500 dark:text-zinc-400">YOUR SOURCES <span>03</span></div>
        <div className="mb-1 flex items-center gap-2.5 rounded-lg border border-transparent px-2.5 py-3 text-[10px] [&_svg]:shrink-0 [&_svg]:text-violet-500 [&_small]:mt-1 [&_small]:block [&_small]:text-[8px] [&_small]:text-stone-500 dark:[&_small]:text-zinc-400 border-violet-200! bg-violet-100/60 dark:border-violet-700/40! dark:bg-violet-400/10"><FileText size={17} /><div>The creative process.pdf<small>12 pages · Ready</small></div><Check size={13} /></div>
        <div className="mb-1 flex items-center gap-2.5 rounded-lg border border-transparent px-2.5 py-3 text-[10px] [&_svg]:shrink-0 [&_svg]:text-violet-500 [&_small]:mt-1 [&_small]:block [&_small]:text-[8px] [&_small]:text-stone-500 dark:[&_small]:text-zinc-400"><Globe2 size={17} /><div>On finding inspiration<small>Web page · Ready</small></div></div>
        <div className="mb-1 flex items-center gap-2.5 rounded-lg border border-transparent px-2.5 py-3 text-[10px] [&_svg]:shrink-0 [&_svg]:text-violet-500 [&_small]:mt-1 [&_small]:block [&_small]:text-[8px] [&_small]:text-stone-500 dark:[&_small]:text-zinc-400"><FileText size={17} /><div>Notes & little observations<small>Text · Ready</small></div></div>
        <div className="mt-3 flex justify-center gap-2 rounded-md border border-dashed border-stone-200 p-2.5 text-[9px] text-stone-500 dark:border-zinc-700 dark:text-zinc-400"><Plus size={15} /> Everything in one place</div>
        <div className="flex items-center gap-3 px-2.5 pt-6 text-stone-400 [&_p]:font-serif [&_p]:text-xs [&_p]:italic [&_p]:leading-relaxed"><BookOpen size={21} /><p>Your ideas deserve<br />a little room to grow.</p></div>
      </aside>
      <div className="px-7 pb-4 pt-6 text-[11px] leading-relaxed max-sm:p-5 [&>p]:mb-2 [&>p]:mt-3 [&>p]:text-stone-500 dark:[&>p]:text-zinc-400 [&_ol]:mb-3 [&_ol]:list-decimal [&_ol]:pl-4 [&_ol]:text-[10px] [&_ol]:text-stone-500 dark:[&_ol]:text-zinc-400 [&_li]:mb-1.5 [&_strong]:font-medium [&_strong]:text-stone-700 dark:[&_strong]:text-zinc-200"><div className="mb-5 ml-auto w-fit rounded-lg rounded-br-sm bg-stone-100 px-3 py-2 text-[10px] dark:bg-zinc-800">What helps us do our most creative work?</div>
        <div className="flex items-center gap-2 text-[11px] font-semibold"><span className="inline-grid size-7 place-items-center rounded-lg bg-violet-100/70 text-violet-600 dark:bg-violet-400/15 dark:text-violet-300"><Sparkles size={15} /></span> A connection worth making</div>
        <p>Creativity starts with paying attention. Across your sources, three ideas keep coming up:</p>
        <ol><li><strong>Make space for curiosity.</strong> Follow the questions, even before you have the answers.</li><li><strong>Collect the small things.</strong> An observation today can become an idea tomorrow.</li><li><strong>Give ideas time.</strong> A little distance often brings a fresh perspective.</li></ol>
        <div className="flex w-fit items-center gap-1.5 rounded border border-stone-200 px-2 py-1 text-[8px] text-violet-500 dark:border-zinc-700 dark:text-violet-300 [&_span]:pl-1 [&_span]:text-stone-400"><FileText size={13} /> The creative process.pdf <span>+ 2 sources</span></div>
        <div className="mt-5 flex items-center justify-between rounded-lg border border-stone-200 px-3 py-2.5 text-[10px] text-stone-400 dark:border-zinc-700 [&>span:last-child]:grid [&>span:last-child]:size-6 [&>span:last-child]:place-items-center [&>span:last-child]:rounded [&>span:last-child]:bg-violet-100 [&>span:last-child]:text-violet-500 dark:[&>span:last-child]:bg-violet-400/15"><span>Follow your next question…</span><span><ArrowRight size={17} /></span></div>
      </div>
    </div>
    <div className="flex items-center justify-between border-t border-stone-200 px-5 py-2.5 text-[8px] text-stone-500 dark:border-zinc-700 dark:text-zinc-400 [&>span:first-child]:flex [&>span:first-child]:items-center [&>span:first-child]:gap-1.5 max-sm:px-3 max-sm:text-[7px]"><span><Sparkles size={12} /> Your sources. A new perspective.</span><span>Illustrative conversation</span></div>
  </div>;
}
export default function Home() {
  const reduce = useReducedMotion();
  return <div className="">
    <section className="relative isolate pt-12 sm:pt-16 mx-auto max-w-6xl px-6 sm:px-10">
      <div className="pointer-events-none absolute inset-x-0 top-0 -z-10 h-[70%] bg-[radial-gradient(ellipse_at_60%_25%,#c5b5e226,transparent_60%)]" aria-hidden="true" />
      <motion.div initial={reduce ? false : { opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .65 }} className="text-center [&>h1]:my-6 [&>h1]:font-serif [&>h1]:text-[clamp(44px,5.5vw,70px)] [&>h1]:font-normal [&>h1]:leading-[1.09] [&>h1]:tracking-[-.045em] [&>p]:text-sm [&>p]:leading-7 [&>p]:text-stone-500 dark:[&>p]:text-zinc-400 [&_em]:text-[#8970b8] dark:[&_em]:text-violet-300">
        <span className="inline-flex items-center gap-2.5 rounded-full border border-stone-200 bg-white px-3 py-2 text-[11px] text-stone-500 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-400"><span className="inline-block size-1.5 rounded-full bg-[#82967a] ring-3 ring-[#82967a15]" /> A quieter way to connect the dots</span>
        <h1>A little clarity for<br />everything you <em>read.</em></h1>
        <p>Bring your documents, notes, and web pages together.<br className="max-sm:hidden" /> Ask a question. Find the insight hiding in the margins.</p>
        <div className="mb-5 mt-7 flex items-center justify-center gap-7 max-sm:flex-col max-sm:gap-4"><Link className="inline-flex min-h-11 items-center justify-center gap-3 rounded-lg border border-transparent bg-[#7861b4] px-5 py-3 text-xs font-medium text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-[#67509f] motion-reduce:transform-none" href="/dashboard">Open your notebook <ArrowUpRight size={18} /></Link><a className="inline-flex items-center gap-2.5 text-xs hover:text-violet-600" href="#how-it-works">See how it works <ArrowRight size={16} /></a></div>
        <div className="flex items-center justify-center gap-5 text-[10px] text-stone-500 max-sm:gap-3 max-sm:text-[9px] dark:text-zinc-400 [&_span]:flex [&_span]:items-center [&_span]:gap-1 [&_svg]:text-[#668778]"><span><Check size={13} /> Answers with sources</span><span><Check size={13} /> Made for your own material</span></div>
      </motion.div>
      <motion.div initial={reduce ? false : { opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .15, duration: .8 }}><NotebookPreview /></motion.div>
      <div className="flex items-center justify-center gap-9 pb-11 pt-8 text-[10px] text-stone-500 max-sm:flex-wrap max-sm:gap-4 dark:text-zinc-400 [&>span]:text-[8px] [&>span]:tracking-widest max-sm:[&>span]:basis-full max-sm:[&>span]:text-center [&>div]:flex [&>div]:items-center [&>div]:gap-2"><span>A HOME FOR WHAT YOU KNOW</span><div><FileText size={15} /> PDFs & documents</div><div><Globe2 size={15} /> Web pages</div><div><BookOpen size={15} /> Notes & ideas</div></div>
    </section>
    <section id="how-it-works" className="border-t border-stone-200 pb-12 pt-16 max-sm:pt-10 dark:border-zinc-800 mx-auto max-w-6xl px-6 sm:px-10">
      <div className="mb-8 flex items-end justify-between gap-6 max-sm:block [&_h2]:mt-4 [&_h2]:font-serif [&_h2]:text-[40px] [&_h2]:leading-tight [&_h2]:tracking-tight [&_em]:text-[#8970b8] dark:[&_em]:text-violet-300 [&>p]:text-xs [&>p]:leading-6 [&>p]:text-stone-500 dark:[&>p]:text-zinc-400 max-sm:[&>p]:mt-4"><div><span className="text-[9px] font-semibold tracking-[.16em] text-stone-500 dark:text-zinc-400">FROM INFORMATION TO UNDERSTANDING</span><h2>Less digging.<br /><em>More discovering.</em></h2></div><p>No complicated setup. Just your material,<br />a little curiosity, and a good question.</p></div>
      <div className="grid grid-cols-3 gap-4 max-sm:grid-cols-1">{[
        [Upload, "01", "Bring it all together", "Drop in a PDF, paste your notes, or add a web page. Give each project a notebook of its own."],
        [MessageSquare, "02", "Ask what’s on your mind", "Get clear answers grounded in your material, or take a quick look at a source summary."],
        [Quote, "03", "Follow the source", "See the passages behind each answer. Spend less time searching and more time making sense of it."]
      ].map(([Icon, num, title, text]) => <article className="rounded-xl border border-stone-200 bg-white p-6 transition hover:border-violet-300 hover:shadow-lg hover:shadow-violet-950/5 dark:border-zinc-800 dark:bg-zinc-900 [&>div]:flex [&>div]:items-center [&>div]:justify-between [&_h3]:mb-2.5 [&_h3]:mt-6 [&_h3]:text-sm [&_h3]:font-medium [&_p]:text-xs [&_p]:leading-6 [&_p]:text-stone-500 dark:[&_p]:text-zinc-400" key={num}><div><span className="grid size-10 place-items-center rounded-xl bg-violet-100/70 text-violet-600 dark:bg-violet-400/15 dark:text-violet-300"><Icon size={22} strokeWidth={1.5} /></span><span className="font-serif text-2xl text-stone-300 dark:text-zinc-600">{num}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div>
    </section>
    <section className="pb-16 pt-10 text-center [&>span]:size-11 [&>h2]:mb-6 [&>h2]:mt-5 [&>h2]:font-serif [&>h2]:text-[40px] [&>h2]:leading-tight [&>h2]:tracking-tight [&_em]:text-[#8970b8] dark:[&_em]:text-violet-300 [&>p]:mt-4 [&>p]:text-[10px] [&>p]:text-stone-500 mx-auto max-w-6xl px-6 sm:px-10"><span className="inline-grid size-7 place-items-center rounded-lg bg-violet-100/70 text-violet-600 dark:bg-violet-400/15 dark:text-violet-300"><Sparkles size={22} /></span><h2>Your next good idea<br />is already <em>in there.</em></h2><Link className="inline-flex min-h-11 items-center justify-center gap-3 rounded-lg border border-transparent bg-[#7861b4] px-5 py-3 text-xs font-medium text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-[#67509f] motion-reduce:transform-none" href="/dashboard">Make room for it <ArrowUpRight size={18} /></Link><p>Start a notebook. See where your curiosity takes you.</p></section>
  </div>;
}
